# File: linux/roles/couchbase-server/centos/vars/main.yml - CentOS variables
#
# A listing of available Couchbase Server Enterprise Edition packages
# and their metadata for CentOS - uncomment 4 lines under *one* version
# entry to install that version of Couchbase Server instead of the default
# which is to install the latest version

# Couchbase Server Enterprise Edition version 2.2.0 on CentOS
#centos:
#  version: 2.2.0
#  package: couchbase-server-enterprise_2.2.0_x86_64.rpm
#  url: http://packages.couchbase.com/releases/2.2.0/couchbase-server-enterprise_2.2.0_x86_64.rpm
#  sha256: 0ce1f9858a3509362a4f7297089c1e18b31056fb3b95f2eea702c2891aa1bc1a

## Couchbase Server Enterprise Edition version 2.1.1
centos:
  version: 2.1.1
  package: couchbase-server-enterprise_x86_64_2.1.1.rpm
  url: http://packages.couchbase.com/releases/2.1.1/couchbase-server-enterprise_x86_64_2.1.1.rpm
  sha256: 03f89821f602902f5d9e9c55b23281c02ca2e88d5bbcf3db45ec83de8146d036

## Couchbase Server Enterprise Edition version 2.1.0
#centos:
#  version: 2.1.0
#  package: couchbase-server-enterprise_x86_64_2.1.0.rpm
#  url: http://packages.couchbase.com/releases/2.1.0/couchbase-server-enterprise_x86_64_2.1.0.rpm
#  sha256: 9c07ecdf558968703723220f024922f9db83b1bd5daf6362d60ded1cd9a0ef84

## Couchbase Server Enterprise Edition version 2.0.1
#centos:
#  version: 2.0.1
#  package: couchbase-server-enterprise_x86_64_2.0.1.rpm
#  url: http://packages.couchbase.com/releases/2.0.1/couchbase-server-enterprise_x86_64_2.0.1.rpm
#  sha256: fa091c587134afa8a9ba853f1ee1cf78dbe3329a808086f3b4541f9ef6fab104

## Couchbase Server Enterprise Edition version 2.0.0
#centos:
#  version: 2.0.0
#  package: couchbase-server-enterprise_x86_64_2.0.0.rpm
#  url: http://packages.couchbase.com/releases/2.0.0/couchbase-server-enterprise_x86_64_2.0.0.rpm
#  sha256: 6cb2a274ca5ab502229be5ab37a891a9c90e56bbcb724f9f09286fde59489767

## Couchbase Server Enterprise Edition version 1.8.1
#centos:
#  version: 1.8.1
#  package: couchbase-server-enterprise_x86_64_1.8.1.rpm
#  url: http://packages.couchbase.com/releases/1.8.1/couchbase-server-enterprise_x86_64_1.8.1.rpm
#  sha256: 3b4f2fec7f50a78575c8c07f246257be5449c2fe7477f01987aa24294a54f456
